### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by JoeZijunZhou**

### CODE REVIEW

**Review by gangji — APPROVED** [review]
Thanks Zijun!

**Comment by vipannalla** [comment]
Can you also update this to make it consistent with README -- https://github.com/google/JetStream/blob/main/setup.py#L29 ?

**Review by vipannalla — APPROVED** [review]
Please update https://github.com/google/JetStream/blob/main/setup.py#L29 before merging.

**Comment by JoeZijunZhou** [comment]
> Please update https://github.com/google/JetStream/blob/main/setup.py#L29 before merging.

Updated.

**Pull request merged**
