### PR TITLE
Ensure server warmup before benchmark

### PR DESCRIPTION
**Pull request by JoeZijunZhou**

### CODE REVIEW

**Comment by hosseinsarshar** [comment]
I think 10 seconds is too long - 2-5 perfectly worked for me.

**Comment by liurupeng** [comment]
after Vivian added the AOT support, could we use that to identify if the replica has warmed up?

**Review by FanhaiLu1 — COMMENTED** [review]
Instead of sleep x seconds, can you wait until all the warm up request return all the tokens?

**Comment by JoeZijunZhou** [comment]
> after Vivian added the AOT support, could we use that to identify if the replica has warmed up?

Yes, that would be the ideal signal to resolve this issue.

**Comment by JoeZijunZhou** [comment]
> Instead of sleep x seconds, can you wait until all the warm up request return all the tokens?

There is a case when the warmup requests done before server warmup complete. Vivian is working on getting the server warmup complete signal from engine. This is a temp workaround.

**Review by FanhaiLu1 — APPROVED** [review]

**Pull request merged**
